services:
  frontend:
    build: 
      context: ../frontend/
      dockerfile: docker/Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - 3000:3000
  backend:
    build: 
      context: ../backend/
      dockerfile: docker/Dockerfile
    volumes:
      - ../backend:/app
    ports:
      - 5001:5001
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: